# Generated by Django 2.1.5 on 2019-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
