# Generated by Django 2.1.5 on 2019-03-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
