# Generated by Django 2.1.5 on 2019-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=100)),
                ('folder', models.CharField(max_length=30)),
                ('storage', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='memory',
            field=models.IntegerField(default=5242880),
        ),
        migrations.AddField(
            model_name='customer',
            name='memory_status',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
