# Generated by Django 2.1.5 on 2019-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20190305_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='folder',
        ),
        migrations.AlterField(
            model_name='customer',
            name='memory',
            field=models.IntegerField(default=0),
        ),
    ]
